"""add tactic_id to mitre_mappings

Revision ID: fe68a179f10c
Revises: 956e583aa776
Create Date: 2026-08-05 17:56:58.361109
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fe68a179f10c"
down_revision: str | None = "956e583aa776"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mitre_mappings", sa.Column("tactic_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mitre_mappings", "tactic_id")
    # ### end Alembic commands ###
