"""confirm real field shapes: numeric ids, is_building_block, owner/origin/dates

Revision ID: 55f4064d9450
Revises: 8c5e534fdf98
Create Date: 2026-08-06 09:57:01.735310
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '55f4064d9450'
down_revision: Union[str, None] = '8c5e534fdf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_blocks_reference', sa.Column('qradar_rule_id', sa.BigInteger(), nullable=False))
    op.add_column('building_blocks_reference', sa.Column('identifier', sa.Text(), nullable=True))
    op.drop_constraint(op.f('uq_bb_reference_customer_bbid'), 'building_blocks_reference', type_='unique')
    op.create_index(op.f('ix_building_blocks_reference_identifier'), 'building_blocks_reference', ['identifier'], unique=False)
    op.create_unique_constraint('uq_bb_reference_customer_ruleid', 'building_blocks_reference', ['customer_id', 'qradar_rule_id'])
    op.drop_column('building_blocks_reference', 'bb_id')
    op.alter_column('rule_offense_contributions', 'qradar_rule_id',
               existing_type=sa.TEXT(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='qradar_rule_id::bigint')
    op.add_column('rules', sa.Column('owner', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('origin', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('linked_rule_identifier', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rules', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('rules', 'qradar_rule_id',
               existing_type=sa.TEXT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='qradar_rule_id::bigint')
    op.drop_column('rules', 'last_event_id')
    op.drop_column('rules', 'last_event_at')
    op.drop_column('rules', 'last_triggered_at')
    op.add_column('rules_reference', sa.Column('identifier', sa.Text(), nullable=True))
    op.alter_column('rules_reference', 'qradar_rule_id',
               existing_type=sa.TEXT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='qradar_rule_id::bigint')
    op.create_index(op.f('ix_rules_reference_identifier'), 'rules_reference', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_reference_identifier'), table_name='rules_reference')
    op.alter_column('rules_reference', 'qradar_rule_id',
               existing_type=sa.BigInteger(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('rules_reference', 'identifier')
    op.add_column('rules', sa.Column('last_triggered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('rules', sa.Column('last_event_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('rules', sa.Column('last_event_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('rules', 'qradar_rule_id',
               existing_type=sa.BigInteger(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('rules', 'updated_at')
    op.drop_column('rules', 'created_at')
    op.drop_column('rules', 'linked_rule_identifier')
    op.drop_column('rules', 'origin')
    op.drop_column('rules', 'owner')
    op.alter_column('rule_offense_contributions', 'qradar_rule_id',
               existing_type=sa.BigInteger(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('building_blocks_reference', sa.Column('bb_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_bb_reference_customer_ruleid', 'building_blocks_reference', type_='unique')
    op.drop_index(op.f('ix_building_blocks_reference_identifier'), table_name='building_blocks_reference')
    op.create_unique_constraint(op.f('uq_bb_reference_customer_bbid'), 'building_blocks_reference', ['customer_id', 'bb_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('building_blocks_reference', 'identifier')
    op.drop_column('building_blocks_reference', 'qradar_rule_id')
    # ### end Alembic commands ###