"""add bb_parsed_at to rules for incremental BB re-parsing

Revision ID: a5d9da13ebe6
Revises: d4e5f6a7b8c9
Create Date: 2026-08-07 08:22:30.299826
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a5d9da13ebe6'
down_revision: str | None = 'd4e5f6a7b8c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('bb_parsed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'bb_parsed_at')
    # ### end Alembic commands ###