"""rename bb_parsed_at to bb_parsed_as_of for clarity

Revision ID: b72350ee8297
Revises: a5d9da13ebe6
Create Date: 2026-08-07 09:27:48.046399
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b72350ee8297"
down_revision: str | None = "a5d9da13ebe6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "building_blocks_reference",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # renamed in place (not drop+add) — preserves existing bb_parsed_at values
    # on real customer data instead of wiping every rule's parse checkpoint
    op.alter_column("rules", "bb_parsed_at", new_column_name="bb_parsed_as_of")
    op.add_column(
        "rules_reference", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rules_reference", "updated_at")
    op.alter_column("rules", "bb_parsed_as_of", new_column_name="bb_parsed_at")
    op.drop_column("building_blocks_reference", "updated_at")
    # ### end Alembic commands ###
