"""move BB parse checkpoint from rules to rule_building_blocks

Revision ID: 1840ebd19dac
Revises: a1da7d1f480e
Create Date: 2026-08-07 09:41:16.299076
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1840ebd19dac'
down_revision: Union[str, None] = 'a1da7d1f480e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_building_blocks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('rules', 'bb_modification_checkpoint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('bb_modification_checkpoint', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('rule_building_blocks', 'updated_at')
    # ### end Alembic commands ###