"""replace custom_event_properties + expressions with one denormalized, customer-scoped table

Revision ID: 202609271707
Revises: 202609111828

Safe to drop-and-rebuild: this data is entirely regenerated by a
full-refresh sync (see custom_property_sync.py's own docstring) --
nothing here is hand-entered or unrecoverable. A fresh sync run
repopulates everything immediately after this migration.
"""

import sqlalchemy as sa

from alembic import op

revision = "202609271707"
down_revision = "202609111828"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_table("custom_event_property_expressions")
    op.drop_table("custom_event_properties")

    op.create_table(
        "custom_event_property_expressions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), primary_key=True),
        sa.Column(
            "customer_id",
            sa.Integer(),
            sa.ForeignKey("customers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # Denormalized from the old parent table -- repeated per row
        # deliberately, safe here since this is a full-refresh sync,
        # not hand-maintained data.
        sa.Column("property_qradar_identifier", sa.Text(), nullable=False),
        sa.Column("property_name", sa.Text(), nullable=True),
        sa.Column("property_type", sa.Text(), nullable=True),
        sa.Column("use_for_rule_engine", sa.Boolean(), nullable=True),
        sa.Column("is_builtin_field", sa.Boolean(), nullable=False, server_default="false"),
        # The expression itself
        sa.Column("qradar_identifier", sa.Text(), nullable=False),
        sa.Column("expression_type", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("log_source_type_id", sa.Integer(), nullable=True),
        sa.Column("log_source_id", sa.Integer(), nullable=True),
        sa.Column("qid", sa.Integer(), nullable=True),
        sa.Column("low_level_category_id", sa.Integer(), nullable=True),
        # Flattened, type-specific -- only the relevant columns
        # populated per expression_type, per our confirmed real data:
        # regex uses regex/capture_group/format_string; nvp uses
        # expression/delimiter_pair/delimiter_name_value; everything
        # else (json/xml/cef/leef/aql) uses expression alone.
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("regex", sa.Text(), nullable=True),
        sa.Column("capture_group", sa.Integer(), nullable=True),
        sa.Column("format_string", sa.Text(), nullable=True),
        sa.Column("delimiter_pair", sa.Text(), nullable=True),
        sa.Column("delimiter_name_value", sa.Text(), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )

    op.create_index(
        "ix_cepe_customer_log_source_type",
        "custom_event_property_expressions",
        ["customer_id", "log_source_type_id"],
    )
    op.create_index(
        "ix_cepe_customer_log_source",
        "custom_event_property_expressions",
        ["customer_id", "log_source_id"],
    )


def downgrade() -> None:
    op.drop_table("custom_event_property_expressions")

    # Recreate the two tables exactly as they were at the previous revision
    # (created in 0019, is_builtin_field added in 0020), so a downgraded
    # database is a valid 0031 database that can be upgraded again. They
    # come back EMPTY: the merged rows can't be split back losslessly --
    # re-run the custom property sync after downgrading.
    op.create_table(
        "custom_event_properties",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "customer_id",
            sa.Integer(),
            sa.ForeignKey("customers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("qradar_identifier", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("property_type", sa.Text(), nullable=True),
        sa.Column("use_for_rule_engine", sa.Boolean(), nullable=True),
        sa.Column("datetime_format", sa.Text(), nullable=True),
        sa.Column("locale", sa.Text(), nullable=True),
        sa.Column("auto_discovered", sa.Boolean(), nullable=True),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("is_builtin_field", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.UniqueConstraint(
            "customer_id",
            "qradar_identifier",
            name="uq_custom_event_properties_customer_identifier",
        ),
    )
    op.create_index(
        "ix_custom_event_properties_customer_id", "custom_event_properties", ["customer_id"]
    )

    op.create_table(
        "custom_event_property_expressions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "property_id",
            sa.Integer(),
            sa.ForeignKey("custom_event_properties.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("qradar_identifier", sa.Text(), nullable=False),
        sa.Column("expression_type", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("log_source_type_id", sa.Integer(), nullable=True),
        sa.Column("log_source_id", sa.Integer(), nullable=True),
        sa.Column("qid", sa.Integer(), nullable=True),
        sa.Column("low_level_category_id", sa.Integer(), nullable=True),
        sa.Column("type_specific_data", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index(
        "ix_custom_event_property_expressions_property_id",
        "custom_event_property_expressions",
        ["property_id"],
    )
    op.create_index(
        "ix_custom_event_property_expressions_log_source_type_id",
        "custom_event_property_expressions",
        ["log_source_type_id"],
    )
