"""move reparse decision to rules.needs_reparse, made at ingest time

Revision ID: 5451873af191
Revises: 1840ebd19dac
Create Date: 2026-08-07 11:34:14.073005
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5451873af191'
down_revision: Union[str, None] = '1840ebd19dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_building_blocks', 'updated_at')
    # server_default=true is required here: this is a NOT NULL column being
    # added to an already-populated table (real customer data already has
    # 576+ rows). Every existing row starts as needing a parse, which is
    # semantically correct anyway — this new decision logic has never run
    # against them before.
    op.add_column('rules', sa.Column('needs_reparse', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'needs_reparse')
    op.add_column('rule_building_blocks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###