"""initial schema

Revision ID: c7097f2544b3
Revises: 
Create Date: 2026-08-05 11:25:10.498619
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c7097f2544b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # needed for pgp_sym_encrypt/decrypt on customer_credentials.token_encrypted
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('qradar_host', sa.Text(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('building_blocks_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bb_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'bb_id', name='uq_bb_reference_customer_bbid')
    )
    op.create_index(op.f('ix_building_blocks_reference_customer_id'), 'building_blocks_reference', ['customer_id'], unique=False)
    op.create_table('customer_credentials',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('qradar_rule_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_id', sa.Text(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_xml', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'qradar_rule_id', name='uq_rules_customer_ruleid')
    )
    op.create_index(op.f('ix_rules_customer_id'), 'rules', ['customer_id'], unique=False)
    op.create_table('rules_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('qradar_rule_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'qradar_rule_id', name='uq_rules_reference_customer_ruleid')
    )
    op.create_index(op.f('ix_rules_reference_customer_id'), 'rules_reference', ['customer_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_customer_id'), 'sync_runs', ['customer_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_ref', sa.Text(), nullable=False),
    sa.Column('check_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_customer_id'), 'validation_results', ['customer_id'], unique=False)
    op.create_index(op.f('ix_validation_results_entity_ref'), 'validation_results', ['entity_ref'], unique=False)
    op.create_index(op.f('ix_validation_results_entity_type'), 'validation_results', ['entity_type'], unique=False)
    op.create_table('mitre_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('technique_id', sa.Text(), nullable=True),
    sa.Column('technique_name', sa.Text(), nullable=True),
    sa.Column('tactic', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_mappings_customer_id'), 'mitre_mappings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_mitre_mappings_rule_id'), 'mitre_mappings', ['rule_id'], unique=False)
    op.create_table('rule_building_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('bb_id', sa.Text(), nullable=False),
    sa.Column('raw_xml_snippet', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_building_blocks_bb_id'), 'rule_building_blocks', ['bb_id'], unique=False)
    op.create_index(op.f('ix_rule_building_blocks_rule_id'), 'rule_building_blocks', ['rule_id'], unique=False)
    op.create_table('rule_offense_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('offense_id', sa.Text(), nullable=True),
    sa.Column('contribution', sa.Numeric(), nullable=True),
    sa.Column('raw_xml', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_offense_contributions_rule_id'), 'rule_offense_contributions', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_offense_contributions_rule_id'), table_name='rule_offense_contributions')
    op.drop_table('rule_offense_contributions')
    op.drop_index(op.f('ix_rule_building_blocks_rule_id'), table_name='rule_building_blocks')
    op.drop_index(op.f('ix_rule_building_blocks_bb_id'), table_name='rule_building_blocks')
    op.drop_table('rule_building_blocks')
    op.drop_index(op.f('ix_mitre_mappings_rule_id'), table_name='mitre_mappings')
    op.drop_index(op.f('ix_mitre_mappings_customer_id'), table_name='mitre_mappings')
    op.drop_table('mitre_mappings')
    op.drop_index(op.f('ix_validation_results_entity_type'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_entity_ref'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_customer_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_sync_runs_customer_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_rules_reference_customer_id'), table_name='rules_reference')
    op.drop_table('rules_reference')
    op.drop_index(op.f('ix_rules_customer_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('customer_credentials')
    op.drop_index(op.f('ix_building_blocks_reference_customer_id'), table_name='building_blocks_reference')
    op.drop_table('building_blocks_reference')
    op.drop_table('customers')
    # ### end Alembic commands ###