"""add dedup constraints for offense contributions and mitre mappings

Revision ID: 192964212f92
Revises: 55f4064d9450
Create Date: 2026-08-06 10:15:47.429758
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '192964212f92'
down_revision: Union[str, None] = '55f4064d9450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mitre_mappings', 'tactic_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('mitre_mappings', 'technique_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_mitre_mappings_rule_tactic_technique', 'mitre_mappings', ['rule_id', 'tactic_id', 'technique_id'])
    op.add_column('rule_offense_contributions', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.alter_column('rule_offense_contributions', 'qradar_contribution_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_rule_offense_contributions_customer_id'), 'rule_offense_contributions', ['customer_id'], unique=False)
    op.create_unique_constraint('uq_offense_contrib_customer_contribid', 'rule_offense_contributions', ['customer_id', 'qradar_contribution_id'])
    op.create_foreign_key(
        'fk_offense_contrib_customer_id', 'rule_offense_contributions', 'customers',
        ['customer_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_offense_contrib_customer_id', 'rule_offense_contributions', type_='foreignkey')
    op.drop_constraint('uq_offense_contrib_customer_contribid', 'rule_offense_contributions', type_='unique')
    op.drop_index(op.f('ix_rule_offense_contributions_customer_id'), table_name='rule_offense_contributions')
    op.alter_column('rule_offense_contributions', 'qradar_contribution_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('rule_offense_contributions', 'customer_id')
    op.drop_constraint('uq_mitre_mappings_rule_tactic_technique', 'mitre_mappings', type_='unique')
    op.alter_column('mitre_mappings', 'technique_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('mitre_mappings', 'tactic_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###