"""add log_source_types_reference table

Revision ID: b53430f4243a
Revises: a73bbda79029
Create Date: 2026-08-11 06:05:46.366036
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b53430f4243a'
down_revision: Union[str, None] = 'a73bbda79029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_source_types_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('qradar_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('custom', sa.Boolean(), nullable=True),
    sa.Column('internal', sa.Boolean(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'qradar_type_id')
    )
    op.create_index(op.f('ix_log_source_types_reference_customer_id'), 'log_source_types_reference', ['customer_id'], unique=False)
    op.create_index(op.f('ix_log_source_types_reference_name'), 'log_source_types_reference', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_source_types_reference_name'), table_name='log_source_types_reference')
    op.drop_index(op.f('ix_log_source_types_reference_customer_id'), table_name='log_source_types_reference')
    op.drop_table('log_source_types_reference')
    # ### end Alembic commands ###