"""rename bb_parsed_as_of to bb_modification_checkpoint

Revision ID: a1da7d1f480e
Revises: b72350ee8297
Create Date: 2026-08-07 09:29:56.221978
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a1da7d1f480e'
down_revision: Union[str, None] = 'b72350ee8297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # renamed in place — preserves existing checkpoint values instead of wiping them
    op.alter_column('rules', 'bb_parsed_as_of', new_column_name='bb_modification_checkpoint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'bb_modification_checkpoint', new_column_name='bb_parsed_as_of')
    # ### end Alembic commands ###