"""fix rule_offense_contributions to match real API

Revision ID: 956e583aa776
Revises: c7097f2544b3
Create Date: 2026-08-05 13:37:28.031014
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '956e583aa776'
down_revision: Union[str, None] = 'c7097f2544b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_offense_contributions', sa.Column('qradar_contribution_id', sa.BigInteger(), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('qradar_rule_id', sa.Text(), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('rule_name', sa.Text(), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('rule_type', sa.Text(), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('event_count', sa.Integer(), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('first_event_epoch_ms', sa.BigInteger(), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('last_event_epoch_ms', sa.BigInteger(), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('first_event_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('rule_offense_contributions', 'contribution')
    op.drop_column('rule_offense_contributions', 'raw_xml')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_offense_contributions', sa.Column('raw_xml', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rule_offense_contributions', sa.Column('contribution', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('rule_offense_contributions', 'raw_json')
    op.drop_column('rule_offense_contributions', 'last_event_at')
    op.drop_column('rule_offense_contributions', 'first_event_at')
    op.drop_column('rule_offense_contributions', 'last_event_epoch_ms')
    op.drop_column('rule_offense_contributions', 'first_event_epoch_ms')
    op.drop_column('rule_offense_contributions', 'event_count')
    op.drop_column('rule_offense_contributions', 'rule_type')
    op.drop_column('rule_offense_contributions', 'rule_name')
    op.drop_column('rule_offense_contributions', 'qradar_rule_id')
    op.drop_column('rule_offense_contributions', 'qradar_contribution_id')
    # ### end Alembic commands ###