"""classify rules vs building blocks, fix rules payload format

Revision ID: 8c5e534fdf98
Revises: fe68a179f10c
Create Date: 2026-08-05 18:00:09.135008
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8c5e534fdf98'
down_revision: Union[str, None] = 'fe68a179f10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('identifier', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('object_type', sa.Text(), server_default='RULE', nullable=False))
    op.add_column('rules', sa.Column('building_block_subtype', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_rules_identifier'), 'rules', ['identifier'], unique=False)
    op.drop_column('rules', 'raw_xml')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('raw_xml', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_rules_identifier'), table_name='rules')
    op.drop_column('rules', 'raw_json')
    op.drop_column('rules', 'building_block_subtype')
    op.drop_column('rules', 'object_type')
    op.drop_column('rules', 'identifier')
    # ### end Alembic commands ###