"""Check that the ORM models and the migrations describe the same database.

  uv run python scripts/check_schema_drift.py                    # check (CI runs this)
  uv run python scripts/check_schema_drift.py --update-baseline  # accept the current list

Builds a throwaway database (<db>_drift_check) from an empty database with
`alembic upgrade head`, compares it with the ORM models (Alembic's own
autogenerate comparison, the same one `alembic check` uses), and compares
the differences with the known list in docs/database/schema_drift_baseline.txt:

  a difference not in the baseline     -> FAIL: new drift was introduced
  a baseline line that no longer occurs -> FAIL: it was fixed; remove the line
  exactly the baseline                  -> OK

The baseline can only shrink: every fix must remove its line, so fixed drift
can't quietly come back. The real database is never touched.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from alembic.autogenerate import compare_metadata  # noqa: E402
from alembic.migration import MigrationContext  # noqa: E402
from pgvector.sqlalchemy import (
    Vector,  # noqa: E402,F401 -- lets reflection recognize 'vector' columns
)
from sqlalchemy import create_engine, text  # noqa: E402

import app.db.models  # noqa: E402,F401 -- registers every model on Base.metadata
from app.core.config import settings  # noqa: E402
from app.db.base import Base  # noqa: E402

BASELINE = ROOT / "docs" / "database" / "schema_drift_baseline.txt"
DRIFT_DB = settings.postgres_db_name + "_drift_check"
HEADER = """\
# Known differences between the ORM models (app/db/models) and the database
# the migrations build. Generated by scripts/check_schema_drift.py.
#
# CI fails on any difference NOT listed here, and on any listed line that no
# longer occurs (remove it -- the list may only shrink). Phase 2+ of the
# database redesign (docs/database/design.md) works this list down to empty.
#
# Reading a line: "<what Alembic would do to make the DATABASE match the MODELS>".
#   add_table x      -> model exists, migrations never create the table
#   remove_table x   -> migrations create the table, no model exists
#   add_* / remove_* -> same, for columns, indexes, constraints, foreign keys
#   modify_*         -> both exist but differ (type, nullability, default)
"""


def dsn(db: str) -> str:
    return settings.pg_dsn.rsplit("/", 1)[0] + f"/{db}"


def build_database() -> None:
    admin = create_engine(dsn("postgres"), isolation_level="AUTOCOMMIT")
    with admin.connect() as c:
        c.execute(text(f'DROP DATABASE IF EXISTS "{DRIFT_DB}" WITH (FORCE)'))
        c.execute(text(f'CREATE DATABASE "{DRIFT_DB}"'))
    admin.dispose()
    env = {**os.environ, "POSTGRES_DB_NAME": DRIFT_DB}
    r = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=ROOT,
        env=env,
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        sys.exit(f"FAILED: alembic upgrade head on {DRIFT_DB}:\n{(r.stderr or r.stdout)[-1500:]}")


def _cols(items) -> str:
    return ",".join(c.name if hasattr(c, "name") else str(c) for c in items)


def describe(diff) -> str:
    """One stable, readable line per difference (no memory addresses)."""
    op = diff[0]
    if op in ("add_table", "remove_table"):
        return f"{op} {diff[1].name}"
    if op in ("add_column", "remove_column"):
        return f"{op} {diff[2]}.{diff[3].name}"
    if op in ("add_index", "remove_index"):
        ix = diff[1]
        return f"{op} {ix.table.name}.{ix.name}({_cols(ix.expressions)}){' unique' if ix.unique else ''}"
    if op in ("add_constraint", "remove_constraint"):
        con = diff[1]
        return f"{op} {con.table.name}.{con.name}({_cols(con.columns)})"
    if op in ("add_fk", "remove_fk"):
        fk = diff[1]
        target = fk.elements[0].target_fullname.rsplit(".", 1)[0] if fk.elements else "?"
        return f"{op} {fk.parent.name}({_cols(fk.columns)}) -> {target}({','.join(e.column.name for e in fk.elements)})"
    if op.startswith("modify_"):
        _, _, table, column, _, old, new = diff
        return f"{op} {table}.{column}: {old} -> {new}"
    return f"{op} {diff!r}"


def current_drift() -> list[str]:
    engine = create_engine(dsn(DRIFT_DB))
    try:
        with engine.connect() as conn:
            ctx = MigrationContext.configure(conn, opts={"compare_type": True})
            diffs = compare_metadata(ctx, Base.metadata)
    finally:
        engine.dispose()
    flat = []
    for d in diffs:
        flat.extend(d if isinstance(d, list) else [d])  # modify_* come grouped per column
    return sorted({describe(d) for d in flat})


def read_baseline() -> list[str]:
    if not BASELINE.exists():
        return []
    return sorted(
        line.strip()
        for line in BASELINE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="write the current differences as the baseline",
    )
    args = parser.parse_args()

    build_database()
    current = current_drift()

    if args.update_baseline:
        BASELINE.write_text(
            HEADER + "\n" + "\n".join(current) + "\n", encoding="utf-8", newline="\n"
        )
        print(
            f"Baseline written: {len(current)} known difference(s) in {BASELINE.relative_to(ROOT)}"
        )
        return

    baseline = read_baseline()
    new, fixed = sorted(set(current) - set(baseline)), sorted(set(baseline) - set(current))
    if new:
        print("NEW schema drift (not in the baseline):")
        for line in new:
            print(f"  + {line}")
        print("Write a migration for the model change, or fix the model.\n")
    if fixed:
        print("FIXED drift still listed in the baseline (great -- remove these lines):")
        for line in fixed:
            print(f"  - {line}")
        print(f"Remove them from {BASELINE.relative_to(ROOT)}.\n")
    if new or fixed:
        sys.exit(1)
    print(
        f"OK: models and migrations differ only by the {len(baseline)} known difference(s) in the baseline."
    )


if __name__ == "__main__":
    main()
